### ISSUE TITLE
麻烦把 $router 改名成 router 之类的，不要包含 $ 符号

### ISSUE THREAD

**Issue by Garfield550** [so-diao/taro-report#1]
它在 Unix Shell 里有特殊用途，在 Unix Shell 里 `git checkout $router` 是不能检出你的分支的。

**Comment by so-diao** [comment]
> 它在 Unix Shell 里有特殊用途，在 Unix Shell 里 `git checkout $router` 是不能检出你的分支的。

好的，已去除$符号
